// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNs2-Bqt_Nd-sVejKsvdDZoii7Oj74dQM',
    appId: '1:968459670729:web:6aa028a2dd7f4ea2efe918',
    messagingSenderId: '968459670729',
    projectId: 'doctor-appointment-de62a',
    authDomain: 'doctor-appointment-de62a.firebaseapp.com',
    storageBucket: 'doctor-appointment-de62a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBepfY2yM4H1iRpW-Zm7FbDMNJl_Cdte8s',
    appId: '1:968459670729:android:108673a5cfdd031defe918',
    messagingSenderId: '968459670729',
    projectId: 'doctor-appointment-de62a',
    storageBucket: 'doctor-appointment-de62a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdJfDbY2UpktgHVkCymFrq5XLP_I-GjkI',
    appId: '1:968459670729:ios:9f29a6b27b4329d2efe918',
    messagingSenderId: '968459670729',
    projectId: 'doctor-appointment-de62a',
    storageBucket: 'doctor-appointment-de62a.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdJfDbY2UpktgHVkCymFrq5XLP_I-GjkI',
    appId: '1:968459670729:ios:9f29a6b27b4329d2efe918',
    messagingSenderId: '968459670729',
    projectId: 'doctor-appointment-de62a',
    storageBucket: 'doctor-appointment-de62a.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNs2-Bqt_Nd-sVejKsvdDZoii7Oj74dQM',
    appId: '1:968459670729:web:a31eeb1c1d811ff4efe918',
    messagingSenderId: '968459670729',
    projectId: 'doctor-appointment-de62a',
    authDomain: 'doctor-appointment-de62a.firebaseapp.com',
    storageBucket: 'doctor-appointment-de62a.firebasestorage.app',
  );
}
